#cloud-config

# init-node.sh
package_update: true
preserve_hostname: false
hostname: test-node-vm #ENV

# init-users.sh
users:
  - name: nodeadm #ENV
    gecos: Node admin
    groups: users, sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-rsa your-public-ssh-key AAAAE2VjZHNhLX...etc...== user@host
disable_root: true
ssh_pwauth: false

network:
  version: 2
  ethernets:
    enp0s8:
      dhcp4: false
      addresses:
        - 10.0.1.10/24
      gateway4: 10.0.1.1
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
      routes:
        - to: 10.0.1.0/24
          via: 10.0.1.1
          metric: 1

# # init-finish.sh
# phone_home:
#     url: http://example.com/$INSTANCE_ID/
#     post:
#         - instance_id
#         - hostname
#         - fqdn
#     tries: 5

power_state:
  delay: now
  mode: reboot

# runcmd:
#   - echo 'cloud-init runcmd' >> /var/log/cloud-init-vagrant.log
#   - date >> /var/log/cloud-init-vagrant.log

#

# power_state:
#     delay: 30
#     mode: reboot
#     message: Rebooting machine
#     condition: test -f /var/tmp/reboot_me

# phone_home:
#     url: http://example.com/$INSTANCE_ID/
#     post:
#         - instance_id
#         - hostname
#         - fqdn
#     tries: 5
