version: "3"
services:
  iac-dev-container:
    container_name: IaCDevContainer
    image: ghcr.io/maxotta/iac-development-container:latest
    volumes:
      - "iac-dev-container-data:/var/iac-dev-container-data"
      - "../..:/workspace"
volumes:
  iac-dev-container-data:
    external: false

